apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
      - image: gcr.io/xenon-blade-165218/github-remonlam-itg17-demo:devstuff 
        name: webapp
        env:
        ports:
        - containerPort: 80
          name: webapp
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
    - port: 80
  selector:
    app: webapp
    tier: frontend
  type: LoadBalancer
